# vim: ft=yaml.docker-compose
---
name: technitium

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml

services:
  technitium:
    image: technitium/dns-server:latest
    environment:
      # note that these values are only used for initializing the system
      # they do not take effect if /etc/dns already exists
      DNS_SERVER_DOMAIN: ${COMPOSE_PROJECT_NAME}.ipn.rahulsalvi.com
      DNS_SERVER_PREFER_IPV6: true
      DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES: 127.0.0.1
      DNS_SERVER_WEB_SERVICE_HTTP_PORT: 8080
    volumes:
      - technitium_data:/etc/dns
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

volumes:
  technitium_data:
